Update README, cleanup CODEOWNERS
defenseunicorns/pkg pull request #92
Opened 2024-05-23 20:27 UTC by Noxsios

## Description

Some README + CODEOWNERS cleanup.

2024-06-03 18:56 UTC, lucasrod16 requested changes

2024-06-03 18:56 UTC, lucasrod16 commented on CODEOWNERS
Looks like we should either give @austenbryan write access to the repo or remove from CODEOWNERS file

<img width="857" alt="codeowners" src="https://github.com/defenseunicorns/pkg/assets/87675701/c348c670-b825-4089-9881-919a7ef710db">

2025-04-17 21:15 UTC, daveworth approved these changes

2025-04-18 15:01 UTC, Racer159 approved these changes
Approving for the doc changes - the CODEOWNERS should possibly also include UDS CLI folks as they use these libs as well (in UDS CLI and Maru).

2025-04-21 15:51 UTC, austenbryan approved these changes
Dropping me as code owner and added Dave

2025-04-21 15:52 UTC, merged