Add Kubernetes package with wait logic
defenseunicorns/pkg pull request #98
Opened 2024-06-05 10:40 UTC by phillebaba

## Description

This change adds a new Kubernetes package meant for related logic. It also adds a new Waiter struct which allows users to easily wait for resources to be properly reconciled.

## Related Issue

Relates to #https://github.com/defenseunicorns/zarf/pull/2580
Relates to #https://github.com/defenseunicorns/lula/issues/229

2024-06-05 10:41 UTC, phillebaba commented
I am a bit unsure if having a single struct for just waiting is a good idea, but we can always deprecate it in the future and replace it with something else if we see the need. It is better to enable others to easily get the waiting logic first.

2024-06-06 12:08 UTC, AustinAbro321 requested changes

2024-06-06 12:08 UTC, AustinAbro321 commented on .github/workflows/check-kubernetes.yaml
This is a duplicate

2024-06-06 12:41 UTC, phillebaba commented on .github/workflows/check-kubernetes.yaml
Why does the check workflow exist for the other packages?

2024-06-06 13:57 UTC, AustinAbro321 submitted a review, later dismissed

2024-06-06 13:57 UTC, AustinAbro321 commented on .github/workflows/check-kubernetes.yaml
nvm

2024-06-06 19:00 UTC, lucasrod16 requested changes
I'm okay with coming back to add a usage example for this code at later time because we may have to make some changes when we integrate this logic into Zarf

2024-06-06 19:00 UTC, lucasrod16 commented on kubernetes/go.mod
We should be able to avoid introducing new CVEs and make CI happy by upgrading some deps:

```shell
cd kubernetes
go get -u golang.org/x/net
go get -u google.golang.org/protobuf
go mod tidy
```

https://github.com/defenseunicorns/pkg/actions/runs/9386478145/job/25890442133?pr=98#step:4:15

2024-06-06 19:00 UTC, lucasrod16 commented on kubernetes/kubernetes.go
> +package kubernetes
lint error

https://github.com/defenseunicorns/pkg/actions/runs/9386478151/job/25890442674?pr=98#step:7:9

2024-06-06 19:00 UTC, lucasrod16 commented on kubernetes/wait.go
> +		func(statusCollector *collector.ResourceStatusCollector, e event.Event) {
lint error

https://github.com/defenseunicorns/pkg/actions/runs/9386478151/job/25890442674?pr=98#step:7:9

2024-06-07 15:03 UTC, lucasrod16 approved these changes

2024-06-07 15:09 UTC, merged